config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :sessions], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :websites

  resources :publications

  resources :ratings

  resources :recipes do
    get 'new_publication', on: :collection
    post 'create_publication', on: :collection
  end


  root 'recipes#index'

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  has_many :recipe
  validates_presence_of :name
  validates_presence_of :author
  validates_presence_of :edition
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /publications
  def index
    @publications = Publication.order('LOWER(name)')
  end

  # GET /publications/1
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  def create
    @publication = Publication.new(params_for_create)
    if @publication.save
      redirect_to @publication, notice: 'Publication was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /publicationa/1
  def update
    if @publication.update(params_for_update)
      redirect_to @publication, notice: 'Publication was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /publications/1
  def destroy
    @publication.destroy
    redirect_to publications_url, notice: 'Publication was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_publication
    @publication = Publication.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def params_for_update
    params.require(:publication).permit(:name, :author, :edition)
  end

  def params_for_create
    params.require(:publication).permit(:name, :author, :edition)
  end
end

app/views/publications/_form.html.slim
= simple_form_for(@publication, html: { class: 'form-vertical' }, wrapper: :vertical_form) do |f|
  = f.error_notification

  #new_publication_inputs.form-inputs
    = f.input :name
    = f.input :author
    = f.input :edition
  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/publications/edit.html.slim
h1.h2 Edit Publication

== render 'form'
br
.btn-toolbar
  .btn-group
    = link_to 'Show', @publication, class: 'btn btn-info'
  .btn-group
    = link_to 'Back', publications_path, class: 'btn btn-info'

app/views/publications/index.html.slim
.row
  h1.h2 Publications
  = link_to 'New Publication', new_publication_path, class: 'btn btn-info'
.row
    - @publications.each do |publication|
        h2.h4 = link_to publication.name, edit_publication_path(publication)
        div = publication.author 
        - if publication.edition
          div = publication.edition
.row
  br
  = link_to 'New Publication', new_publication_path, class: 'btn btn-info'

app/views/publications/new.html.slim
h1.h2 New publication

== render 'form'
br
= link_to 'Back', publications_path, class: 'btn btn-info'

app/views/publications/show.html.slim
.row
  h1.h2 = link_to @publication.name, edit_publication_path(@publication)
  div = @publication.author 
  div = @publication.edition
  br
.row
  = link_to 'Back', publications_path, class: 'btn btn-info'