config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :sessions], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :websites

  resources :publications

  resources :ratings

  resources :recipes do
    get 'new_publication', on: :collection
    post 'create_publication', on: :collection
  end


  root 'recipes#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :rememberable, :omniauthable, omniauth_providers: [:google_oauth2, :windowslive]
  has_many :ratings
  has_many :recipes, through: :ratings

  OAUTH_INFOS = {
    google_oauth2: {
      email:      'data.info.email',
      first_name: 'data.info.first_name',
      last_name:  'data.info.last_name'
    }.freeze,
    windowslive: {
      email:      'data.extra.raw_info.emails.preferred',
      first_name: 'data.extra.raw_info.first_name',
      last_name:  'data.extra.raw_info.last_name'
    }.freeze
  }.freeze

  class << self
    OAUTH_INFOS.each do |provider, infos|
      class_eval %"
        def find_for_#{provider}(data, signed_in_resource=nil)
          where(email: #{infos[:email]}).first do |u|
            u.provider   = '#{provider}'
            u.first_name = #{infos[:first_name]}.presence || 'John'
            u.last_name  = #{infos[:last_name]}.presence  || 'Do'
            u.encrypted_password   = Devise.friendly_token[0,20]
          end
        end
      "
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    PROVIDER_KIND_NAMES = {
      google_oauth2: 'Google',
      windowslive:   'Windows Live'
    }.freeze

    User::OAUTH_INFOS.keys.each do |provider|
      kind_name = PROVIDER_KIND_NAMES[provider]
      class_eval %"
      def #{provider}
        @user = User.find_for_#{provider}(request.env['omniauth.auth'], current_user)

        if  @user
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: '#{kind_name}'
          sign_in_and_redirect @user, event: :authentication
        else
          flash[:alert] = 'You need to be invited to access Good Grub'
          redirect_to new_user_session_url
        end
      end
      "
    end
  end
end

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br

- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br

- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br

- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br

- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
    br

- if devise_mapping.omniauthable?
  = link_to user_windowslive_omniauth_authorize_path, class: "btn btn-block btn-social btn-microsoft", method: "post"
    i class="fa fa-windows"
    | Sign in with Microsoft
  br
  = link_to user_google_oauth2_omniauth_authorize_path, class: "btn btn-block btn-social btn-google-plus", method: "post"
    i class="fa fa-google-plus"
    | Sign in with Google