config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :sessions], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :websites

  resources :publications

  resources :ratings

  resources :recipes do
    get 'new_publication', on: :collection
    post 'create_publication', on: :collection
  end


  root 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  include PgSearch
  validates_presence_of :name
  validates_numericality_of :page_number, only_integer: true
  validates_numericality_of :preparation_time, only_integer: true, allow_nil: true
  validates_numericality_of :cooking_time, only_integer: true, allow_nil: true
  belongs_to :publication
  has_many :ratings
  has_many :users, through: :ratings

  accepts_nested_attributes_for :publication, reject_if: :all_blank
  accepts_nested_attributes_for :publication, reject_if: :all_blank
  accepts_nested_attributes_for :ratings, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :users

  pg_search_scope :search, against: [:name, :tags],
                  using: {tsearch: {dictionary: 'english'}},
                  associated_against: { publication: [:name, :author], users: [:first_name, :last_name], ratings: [:value] }

  def self.text_search(search)
    puts search
    if search.present?
      search(search)
    else
      order('LOWER(name)')
    end
  end

  def tag_list
    tags.join(',')
  end

  def tag_list=(list)
    self.tags = list.split(',').map(&:strip)
  end

  def rating_for_user(user_id)
    rating = ratings.find_by(user_id: user_id, recipe_id: id)
    rating || ratings.build(user_id:  user_id, recipe_id: id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /recipes
  def index
    # @recipes = Recipe.order('LOWER(name)')
    @recipes = Recipe.text_search(params[:search])
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(params_for_create)
    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(params_for_update)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def params_for_update
    params.require(:recipe).permit(:name, :page_number, :tag_list, :publication_id,
                                   :preparation_time, :cooking_time,
                                   publication_attributes: [:name, :author, :edition])
  end

  def params_for_create
    params.require(:recipe).permit(:name, :tag_list, :publication_id,  :page_number,
                                   :preparation_time, :cooking_time,
                                   publication_attributes: [:name, :author, :edition])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.slim
= simple_form_for(@recipe, html: { class: 'form-vertical' }, wrapper: :vertical_form) do |f|
  = f.error_notification

  #new_recipe_inputs.form-inputs
    = f.input :name
    #publication
      #publication_from_list
        = f.association :publication, label_method: ->(p) {cell(:publication_summary, p)}, collection: Publication.order(:name), prompt: 'Choose an existing publication'
      = link_to_add_association 'add a new publication', f, :publication
    = f.input :page_number
    = f.input :preparation_time, hint: 'minutes'
    = f.input :cooking_time, hint: 'minutes'
    = f.input :tag_list
  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/recipes/_publication_fields.html.slim
.nested-fields
  h2 New publication
  = f.input :name
  = f.input :author
  = f.input :edition
  = link_to_remove_association "select existing publication", f

app/views/recipes/edit.html.slim
h1.h2 Edit Recipe

== render 'form'
br
.btn-toolbar
  .btn-group
    = link_to 'Show', @recipe, class: 'btn btn-info'
  .btn-group
    = link_to 'Back', recipes_path, class: 'btn btn-info'

app/views/recipes/index.html.slim
.row
  h1.h2 Recipes
.row
  = form_tag recipes_path, method: 'get', class: 'form-inline'
    div.form-group
      = label_tag :search, 'Search', class: 'sr-only'
      = text_field_tag :search, params[:search], class: 'form-control'
    = submit_tag 'Search', name: nil, class: 'btn btn-primary'
  br
.row
  = link_to 'New Recipe', new_recipe_path, class: 'btn btn-info'
.row
    - @recipes.each do |recipe|
      h2.h3 = link_to recipe.name, recipe_path(recipe)
      - if recipe.publication
          = raw cell(:recipe_summary, recipe)
      - if recipe.tags.count > 0
        .row
          div.col-sm-12
            span> class="glyphicon glyphicon-tags"
            - recipe.tags.each do |tag|
               span> class="label label-default" = tag
      - if recipe.ratings.count > 0
        span> = recipe.ratings.average(:value)
        span stars
.row
  br
  = link_to 'New Recipe', new_recipe_path, class: 'btn btn-info' if @recipes.length > 0

app/views/recipes/new.html.slim
h1.h2 New recipe

== render 'form'
br
= link_to 'Back', recipes_path, class: 'btn btn-info'

app/views/recipes/show.html.slim
.row
  h1.h2
    = link_to @recipe.name, edit_recipe_path(@recipe)
  - if @recipe.publication
      = raw cell(:recipe_summary, @recipe).call(:author)
      br
      = raw cell(:recipe_summary, @recipe).call(:publication_link)
  br
  - if @recipe.preparation_time
      span> class="glyphicon glyphicon-time"
      span> = sprintf("%s minutes preparation", @recipe.preparation_time.to_i)
      br
  - if @recipe.cooking_time
      span> class="glyphicon glyphicon-time"
      span> = sprintf("%s minutes cooking", @recipe.cooking_time.to_i)
  - if @recipe.tags.count > 0
    .row
      div.col-sm-12
        span> class="glyphicon glyphicon-tags"
        - @recipe.tags.each do |tag|
           span> class="label label-default" = tag
  .ratings
    h2.h3 Ratings
    hr
    .row.rating
      .col-sm-2.well
        span> class="score" = @recipe.ratings.average(:value) || 'N/A'
        span stars
        #rate-button
          button class="btn btn-success"
            span class="glyphicon glyphicon-pencil" Rate
    br
    #rating-form.hidden.row
      .well
        = simple_form_for(@recipe.rating_for_user(current_user.id), validate: true, html: { class: 'form-vertical' }, wrapper: :vertical_form) do |f|
          = f.input :title
          = f.input :value
          = f.input :comments
          = f.hidden_field :user_id
          = f.hidden_field :recipe_id
          = f.button :submit, class: 'btn btn-info'
    #ratings-list
      - @recipe.ratings.select { |r| r.persisted? }.each do |r|
          .panel
            strong>  = r.user.first_name
            strong>  = r.user.last_name
            span>  = r.value
            span>  stars
            div.lead  = r.title
            div
              i  = r.comments
  br
.row
  = link_to 'Back', recipes_path, class: 'btn btn-info'